import Profile from "../../components/Profile.jsx"
import ContextProvider from "@/app/contextapi/ContextProvider.jsx";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div >
      <ContextProvider>
        <Profile />
        {children}
      </ContextProvider>

    </div>
  )
}
