import "../globals.css";
import ContextProvider from "../contextapi/ContextProvider";
export const metadata = {
  title: "Verification",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true">
        <ContextProvider>
          {children}
        </ContextProvider>
      </body>
    </html>
  )
}
